# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      
      - add_ssh_keys:
          fingerprints:
            - "d3:28:56:9d:60:cd:b9:b5:b3:cc:f4:2f:78:49:0d:59"

      - run: 
          name: "Setup custom environment variables"
          command: git config --global push.default simple && git config --global user.email "$email" && git config --global user.name "$name"
        
      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #      - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
      #      - v1-dependencies-

      #- run: yarn install
      - run: sh ./download-minutes.sh
        #mkdir -p $DATE
        #echo "....Downloading IRC logs for $DATE..."
        #curl -# "https://w3c-ccg.s3.digitalbazaar.com/minutes/$DATE-irc.log" > $DATE/irc-raw.log
      

      #- save_cache:
      #    paths:
      #      - node_modules
      #    key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      #- run: yarn test
