name: Download raw minutes

on:
  repository_dispatch:
    types: start
  schedule:
    - cron:  '* * * * *'
      #'*/1 * * * *'
      # 0 18 * * TUE

jobs:
  download-minutes:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup custom environment variables
      run: git config --global push.default simple && git config --global user.email "kimdhamilton@gmail.com" && git config --global user.name "Kimbot"
    - name: Pull raw meeting log file
      env: { DATE: "2020-01-21" }
      run: sh ./download-minutes.sh

  send-email:
    runs-on: ubuntu-latest
    needs: download-minutes
    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v1.3.0
   
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: kimdhamilton
        password: ${{ secrets.password }}
        subject: raw minutes are downloaded!
        body: you need to clean up this shit
        to: kimdhamilton+456@gmail.com
        from: kimdhamilton@gmail.com
        #content_type: # optional, default is text/plain



