name: Download raw minutes

on:
  repository_dispatch:
    types: download_minutes
  #schedule:
  #  - cron:  '*/5 * * * *'
  # 0 18 * * TUE

jobs:
  download-minutes:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup custom environment variables
      run: git config --global push.default simple && git config --global user.email "w3c.ccg@gmail.com" && git config --global user.name "W3C CCG"
    - name: Pull raw meeting log file
      env: 
        DATE: ${{ github.event.client_payload.date }}
      run: bash ./download-minutes.sh

    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Add raw log for telecon [ci skip]
        branch: master

        # Optional git params
        # commit_options: '--no-verify --signoff'

        # Optional glob pattern of files which should be added to the commit
        #file_pattern: irc-raw.log

      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  send-email:
    runs-on: ubuntu-latest
    needs: download-minutes
    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v1.3.0
   
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: w3c.ccg
        password: ${{ secrets.password }}
        subject: W3C CCG raw minutes need to be cleaned up
        body: Go to scribe-tool (https://w3c-ccg.github.io/meetings/scribe-tool/), paste in the contents of irc-raw.log, clean it up, save results in irc.log (same folder) and commit.
        to: w3c.ccg+456@gmail.com
        from: w3c.ccg@gmail.com
        #content_type: # optional, default is text/plain



