name: Publish minutes

on:
  push:
    paths:
    - '**/irc.log'

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup custom environment variables
      run: git config --global push.default simple && git config --global user.email "kimdhamilton@gmail.com" && git config --global user.name "Kimbot"   
    - name: Generate html minutes
      id: generate_html_minutes
      run: |
        npm install
        bash ./generate-html.sh
        echo "##[set-output name=date;]${DATE}"
      env:
        CI: true
        DATE: "2020-01-21"
        
    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Add html minutes for telecon [ci skip]
        branch: master

        # Optional git params
        #commit_options: '--no-verify --signoff'

        # Optional glob pattern of files which should be added to the commit
        #file_pattern: index.html

      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send email
      uses: dawidd6/action-send-mail@v1.3.0
   
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: kimdhamilton
        password: ${{ secrets.password }}
        subject: ${{ format('[MINUTES] W3C Credentials CG Call - {0} 12pm ET', steps.generate_html_minutes.outputs.date) }}
        body: ${{ format('file://{0}/email.log', steps.generate_html_minutes.outputs.date) }}
        to: kimdhamilton+123@gmail.com
        from: kimdhamilton@gmail.com
        #content_type: # optional, default is text/plain
